# -*- coding: utf-8 -*-
"""CS5331_HW2_Fa24(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RUG-XFIfe4QEjf2dUgvgRMyVDDfp8N2i

#Use a proper tensorflow version
Our model was build on TF2.14 and it does cause some compatibility issues with TF2.17 so make sure you use the right version
"""

"""#Check tf version
import tensorflow as tf
#print(tf.__version__)

#The following force you to use tensorflow 2.14 but you need to restart. You may comment it if you know you are using 2.14
##Make sure you down grade!! otherwise, some part will fail due to compatibility.
#!pip3 install --upgrade tensorflow==2.14.0
print(tf.__version__)"""

!pip3 install --upgrade tensorflow==2.14.0

import tensorflow as tf
print(tf.__version__)

"""#Get the dataset"""

# mount google drive on your runtime using and authorization code.
# more details here: https://colab.research.google.com/notebooks/io.ipynb
from google.colab import drive
drive.mount('/content/drive')

#Set directories correctly

import os
# Path to the directory containing the project files (CHANGE THIS PATH TO THE DIRECTORY ON YOUR COMPUTER)
PROJECT_ROOT_DIR = os.getcwd() + '/'

# Path to the directory containing the dataset relative to project file
DATA_DIR = 'drive/MyDrive/CS5331_CS4331/HW1/GTSRB_dataset/'

#path to the directory you want to use for saving models relative to the project file
MODEL_DIR = 'drive/MyDrive/CS5331_CS4331/HW1/GTSRB_dataset/'

# Funciton for loading the dataset
# Code from advml-traffic-sign (https://github.com/inspire-group/advml-traffic-sign)
def load_dataset_GTSRB(n_channel=3, train_file_name=None):
    """
    Load GTSRB data as a (datasize) x (channels) x (height) x (width) numpy
    matrix. Each pixel is rescaled to the range [0,1].
    """

    def load_pickled_data(file, columns):
        """
        Loads pickled training and test data.

        Parameters
        ----------
        file    : string
                          Name of the pickle file.
        columns : list of strings
                          List of columns in pickled data we're interested in.

        Returns
        -------
        A tuple of datasets for given columns.
        """

        with open(file, mode='rb') as f:
            dataset = pickle.load(f)
        return tuple(map(lambda c: dataset[c], columns))

    def preprocess(x, n_channel):
        """
        Preprocess dataset: turn images into grayscale if specified, normalize
        input space to [0,1], reshape array to appropriate shape for NN model
        """

        if n_channel == 3:
            # Scale features to be in [0, 1]
            x = (x / 255.).astype(np.float32)
        else:
            # Convert to grayscale, e.g. single Y channel
            x = 0.299 * x[:, :, :, 0] + 0.587 * x[:, :, :, 1] + \
                0.114 * x[:, :, :, 2]
            # Scale features to be in [0, 1]
            x = (x / 255.).astype(np.float32)
            x = x[:, :, :, np.newaxis]
        return x

    # Load pickle dataset
    if train_file_name is None:
        x_train, y_train = load_pickled_data(
            PROJECT_ROOT_DIR + DATA_DIR + 'train.p', ['features', 'labels'])
    else:
        x_train, y_train = load_pickled_data(
            PROJECT_ROOT_DIR + DATA_DIR + train_file_name, ['features', 'labels'])
    x_val, y_val = load_pickled_data(
        PROJECT_ROOT_DIR + DATA_DIR + 'valid.p', ['features', 'labels'])
    x_test, y_test = load_pickled_data(
        PROJECT_ROOT_DIR + DATA_DIR + 'test.p', ['features', 'labels'])

    # Preprocess loaded data
    x_train = preprocess(x_train, n_channel)
    x_val = preprocess(x_val, n_channel)
    x_test = preprocess(x_test, n_channel)
    return x_train, y_train, x_val, y_val, x_test, y_test

import pickle
import numpy as np
# Load the images and labels. These images are RGB so we have 3 channels
imgs_train, labels_train, imgs_val, labels_val, imgs_test, labels_test = load_dataset_GTSRB(n_channel=3)

"""#Load the built model from Assignment 1 (Already on blackboard)"""

## Load the saved the model
from tensorflow.keras.models import load_model



#load our already trained model
# Your earlier directories should change to match this one
#You should be able to load the model once trained. The following line is used for that.
model = load_model(MODEL_DIR +'VGG_best.h5')

"""#Some constants that you might need
It is not neccessary that you will use all
"""

# Set constants (GTSRB)
NUM_LABELS = 43                             # Number of labels or classes for classification
BATCH_SIZE = 128                            # Size of batch
HEIGHT = 32                                 # Height of input image
WIDTH = 32                                  # Width of input image
N_CHANNEL = 3                               # Number of channels
OUTPUT_DIM = 43                             # Number of output dimension

# Set training hyperparameters
NUM_EPOCH = 50                            # Number of epoch to train
LR = 0.0002                                 # Learning rate
RBW = True #restore best weights
PATIENCE = 5# how many epochs between improvements
sample_size = 100
alpha = 0.001
INPUT_SHAPE = (HEIGHT, WIDTH, N_CHANNEL)  # Input shape of model
IMG_SHAPE = (HEIGHT, WIDTH, N_CHANNEL)

"""# setting up labels"""

from tensorflow.keras.utils import to_categorical

#Convert the labels to one-hot encoding (to input to the models)

#Use the following sub-test dataset for your certified training
imgs_sub_test = imgs_test[0:500,:,:,:].copy()
labels_adv = labels_test[0:500].copy()




labels_train_cat = to_categorical(labels_train, NUM_LABELS)
labels_test_cat = to_categorical(labels_test, NUM_LABELS)
labels_val_cat = to_categorical(labels_val, NUM_LABELS)

#for testing adversarial inputs
labels_adv_cat = to_categorical(labels_adv,NUM_LABELS)

print('Labels train shape: {}'.format(labels_train.shape))
print('Labels train catagorical shape: {}\n'.format(labels_train_cat.shape))
print('Labels Adver shape: {}'.format(labels_adv.shape))
print('Labels Adver catagorical shape: {}'.format(labels_adv_cat.shape))

print('Imgs Adver shape: {}'.format(imgs_sub_test.shape))

"""#Install ART if needed"""

#Install ART
!pip3 install adversarial-robustness-toolbox

#!pip install tensorflow adversarial-robustness-toolbox numpy

#Install ART if you have not done that

#!pip install adversarial-robustness-toolbox

#!pip install adversarial-robustness-toolbox==1.17.0



#!pip install adversarial-robustness-toolbox

#!pip uninstall adversarial-robustness-toolbox
#!pip install git+https://github.com/Trusted-AI/adversarial-robustness-toolbox.git





#from art.attacks import evasion
#print(dir(evasion))


#!pip install adversarial-robustness-toolbox --upgrade


#from art.estimators.certification.randomized_smoothing import *
#print(dir())

"""#Some imports.
You might need more
"""

# Commented out IPython magic to ensure Python compatibility.
from art.estimators.classification import TensorFlowV2Classifier

import numpy as np
# %matplotlib inline
import matplotlib.pyplot as plt

"""###Part 1

##Task 1
Our first task with implement randomized smoothing for the VGG model from last time. Your task is to download the model and use Adversarial Robustness Toolbox (ART) to implement randomized smoothing to certify the model. [This notebook](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/output_randomized_smoothing_mnist.ipynb) should be your guide to implementing the task. You will use σ^2=[ 0.25,0.5,1] as Gaussian noise parameter. Once needed, use 100 as the number of samples to estimate the certifiable radius. You will find the standard and certified accuracy for different noises. You will also plot the L2 radius versus certified accuracy.

#Notes:
Training will take time to generate the results. Try it first with only 2 training rounds and then increase to 25. Certification for all the testing will take forever. Thus, whenever you need a testing set, use a subset of the testing samples, not all. We already provided that subset for you in a variable that you must look for.
"""

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from art.estimators.classification import TensorFlowV2Classifier
from art.estimators.certification.randomized_smoothing import TensorFlowV2RandomizedSmoothing


model = tf.keras.models.load_model(MODEL_DIR + 'VGG_best.h5')

X_test = imgs_sub_test  # The subset of testing samples
y_test = labels_adv     # The corresponding labels

# Parameters for Gaussian noise and randomized smoothing
sigma_values = [0.25, 0.5, 1]
initial_training_rounds = 25
num_certification_samples = 100  # Number of samples for certifiable radius estimation

# Initialize a dictionary to store data for Table 1
table_data = {
    "Model": ["VGG16 original", "Smoothed σ^2=0.25", "Smoothed σ^2=0.5", "Smoothed σ^2=1"],
    "L2 Radius": [0, 0.25, 0.5, 1],
    "Standard Accuracy": [],
    "Standard Coverage Rate": [],
    "Certified Accuracy": []
}




def compute_accuracy(predictions, y_true):
    if predictions.ndim == 1:

        accuracy = np.mean(predictions == y_true)
    else:

        accuracy = np.mean(np.argmax(predictions, axis=1) == y_true)

    coverage = np.mean(predictions >= 0)
    return accuracy, coverage


# Standard accuracy and coverage rate for the original model
predictions = model.predict(X_test)
standard_accuracy, standard_coverage = compute_accuracy(predictions, y_test)
table_data["Standard Accuracy"].append(standard_accuracy)
table_data["Standard Coverage Rate"].append(standard_coverage)
table_data["Certified Accuracy"].append(None)  # No certified accuracy for the original model

# Placeholder for L2 radii and certified accuracies for plotting
l2_radius_range = np.linspace(0, 3, 100)  # L2 radii from 0 to 3 for plotting
certified_accuracies = []

# Apply randomized smoothing to certify the model for each sigma value
for sigma in sigma_values:
    # Initialize ART classifier and smoothed classifier with Gaussian noise
    art_model = TensorFlowV2Classifier(model=model, clip_values=(0, 1), input_shape=INPUT_SHAPE, nb_classes=NUM_LABELS)
    smoothed_model = TensorFlowV2RandomizedSmoothing(model=model, nb_classes=NUM_LABELS,
                                                     input_shape=INPUT_SHAPE, scale=sigma)

    # Perform predictions with smoothing and certify using the specified number of samples
    smoothed_predictions, radii = smoothed_model.certify(X_test, n=num_certification_samples)

    # Calculate standard accuracy, coverage rate, and certified accuracy
    accuracy, coverage = compute_accuracy(smoothed_predictions, y_test)
    certified_accuracy = np.mean(np.array(radii) >= sigma)  # Certified accuracy based on L2 radius ≥ sigma

    # Append the calculated data to the table
    table_data["Standard Accuracy"].append(accuracy)
    table_data["Standard Coverage Rate"].append(coverage)
    table_data["Certified Accuracy"].append(certified_accuracy)

    # Calculate certified accuracy across the L2 radius range for plotting
    certified_acc_by_radius = [np.mean(np.array(radii) >= r) for r in l2_radius_range]
    certified_accuracies.append(certified_acc_by_radius)

# Display Table 1
print("Table 1: Standard and Certified Accuracies for Different Models")
print(f"{'Model':<25}{'L2 Radius':<15}{'Standard Accuracy':<20}{'Standard Coverage Rate':<25}{'Certified Accuracy':<20}")

for i in range(len(table_data["Model"])):
    certified_acc = f"{table_data['Certified Accuracy'][i]:<.4f}" if table_data['Certified Accuracy'][i] is not None else "N/A"
    print(f"{table_data['Model'][i]:<25}{table_data['L2 Radius'][i]:<15.4f}{table_data['Standard Accuracy'][i]:<20.4f}"
          f"{table_data['Standard Coverage Rate'][i]:<25.4f}{certified_acc:<20}")

# Plot L2 Radius vs Certified Accuracy for original and smoothed models
plt.figure(figsize=(10, 6))

plt.plot(l2_radius_range, certified_accuracies[0], label='Smoothed σ=0.25', color='green')
plt.plot(l2_radius_range, certified_accuracies[1], label='Smoothed σ=0.5', color='blue')
plt.plot(l2_radius_range, certified_accuracies[2], label='Smoothed σ=1', color='purple')
plt.xlabel('L2 Radius')
plt.ylabel('Certified Accuracy')
plt.title('L2 Radius vs Certified Accuracy for Different Models')
plt.legend()
plt.grid()
plt.show()







"""##Part 2

##Task 2

Now, let's do some privacy attacks. We will focus on Membership inference attacks. This task will implement label-only attacks, while the next will implement shadow modeling. As discussed in class, the label-only attack is developed based on the fact that it costs an attacker so much to generate a successful adversarial sample for a member sample. In contrast, the cost will be much less for a non-member sample. Thus, it uses HopSkipJump to generate a successful adversarial sample and then measure the perturbation using the L2 norm. If the perturbation is above a threshold, it will be classified as a member; if not, it will be classified as a non-member. Hence, we will follow the following steps to perform the attack (Your reference code is [this notebook](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/label_only_membership_inference.ipynb)):

1-	Generate a dataset (already given): The training and testing datasets are merged into one, with the training classified as members and the testing as non-members. We picked 1500 samples from this dataset to build our attack model.


2-	Calculate the threshold (to be implemented by you): Your task here is to use existing implementations in ART to calculate/calibrate the threshold. All parameters are given to you in the code (in comments).

3-	Infer the data: Now, use the provided 1500 samples to predict whether they are members. Then, compare your performance to the ground truth and present the results.


One parameter you will need to set is the maximum number of queries (used in step 2). Set this parameter to 5 and 10. All that is needed is to answer the questions below.


##Note on resources:
It takes time to generate the adversarial examples. A good GPU computer will take you around 1-3 hours per round. Thus, plan your time accordingly.

#Generate a dataset
"""

##Some variables to set  number of samples used to calibrate distance threshold
x = np.concatenate([imgs_train, imgs_test]) #Merge train and test dataset
y = np.concatenate([labels_train_cat, labels_test_cat]) #Merge train and test dataset
training_sample = np.array([1] * len(imgs_train) + [0] * len(imgs_test)) #Class label for the attack model training. What does it say?

from numpy.random import choice

##Random samples to be used for training our attack model
# evaluation data
n = 1500
eval_data_idx = choice(len(x), n) #choose 1500 of the samples
x_eval, y_eval = x[eval_data_idx], y[eval_data_idx] #creating your training dataset for the attack model
eval_label = training_sample[eval_data_idx] #creating your training label for the attack model

"""#Calculate the threshold"""

from art.attacks.evasion import HopSkipJump
from art.estimators.classification import TensorFlowV2Classifier
import numpy as np


NUM_QUERIES = [5, 10]
TOP_T_PERCENTILE = 20
NUM_CALIBRATION_SAMPLES = 200
BATCH_SIZE = 256
x_train, y_train, x_val, y_val, x_test, y_test = load_dataset_GTSRB(n_channel=3)


x_combined = np.concatenate([x_train, x_test])
y_combined = np.concatenate([y_train, y_test])


membership_labels = np.concatenate([np.ones(len(x_train)), np.zeros(len(x_test))])


attack_indices = np.random.choice(len(x_combined), 1500, replace=False)
x_attack = x_combined[attack_indices]
y_attack = y_combined[attack_indices]
membership_labels_attack = membership_labels[attack_indices]

input_shape = x_train.shape[1:]
num_classes = y_train.shape[-1]

art_model = TensorFlowV2Classifier(
    model=model,
    nb_classes=num_classes,
    input_shape=input_shape,
    clip_values=(0, 1)
)


hsj_attack = HopSkipJump(classifier=art_model, max_iter=1, max_eval=10000, init_eval=100, batch_size=BATCH_SIZE)


for max_queries in NUM_QUERIES:
    perturbations = []

    for i in range(NUM_CALIBRATION_SAMPLES):

        x_adv = hsj_attack.generate(x=np.expand_dims(x_attack[i], axis=0), max_iter=max_queries)
        perturbation = np.linalg.norm((x_adv - x_attack[i]).reshape(-1))
        perturbations.append(perturbation)


    threshold = np.percentile(perturbations, TOP_T_PERCENTILE)
    print(f"Calibrated threshold for max_queries={max_queries}: {threshold}")


    predicted_labels = []
    for i in range(len(x_attack)):

        x_adv = hsj_attack.generate(x=np.expand_dims(x_attack[i], axis=0), max_iter=max_queries)
        perturbation = np.linalg.norm((x_adv - x_attack[i]).reshape(-1))


        predicted_labels.append(1 if perturbation >= threshold else 0)


    members_accuracy = np.mean((np.array(predicted_labels) == 1) & (membership_labels_attack == 1))
    non_members_accuracy = np.mean((np.array(predicted_labels) == 0) & (membership_labels_attack == 0))
    overall_accuracy = np.mean(np.array(predicted_labels) == membership_labels_attack)

    print(f"\nResults for max_queries={max_queries}:")
    print(f"Members accuracy: {members_accuracy}")
    print(f"Non-member accuracy: {non_members_accuracy}")
    print(f"Overall accuracy: {overall_accuracy}")

"""# Infer the data"""



"""##Task 3
Let's do another privacy attack. This time, it is a “shadow models” attack, discussed in class. [This notebook](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/attack_membership_inference_shadow_models.ipynb) will be your guide. You are going to use ART again, and here are a few steps to follow:

1-	Build the shadow models based on the numbers provided below. Set the training ratio for them to 0.5.

2-	Measure the accuracies for them (use validation accuracy as a measure)

3-	Build the attack model. You can build any binary classifier. You are suggested to use a random forest classifier for simplicity.

4-	Evaluate your attack models for members and non-members (the evaluation data is already given to you).

5-	Calculate the precision and recall of your attack model.

Your changing parameter in this task is the number of shadow models. You will set it to 1,2 and 5. Please note the needed metrics so you can plan your code accordingly.

#Note on the implementation:
Our implementation will look strange. Shadow models will require lots and lots of data. Thus, in a general setup, researchers use 80% of the data for shadow models, and only 20% is for training/testing/validation. However, given that we are using a model already built from Assignment 1, we cannot use this general setup. Thus, our shadow models' data will concatenate training and testing while the validation will be left out to test performance accuracy. To evaluate the attack, we generated a separate dataset that is taken from training and testing. You will need to locate and work with that data. In general, your attack results won't be good due to the above design, but the idea is that you should analyze it.

# Data for evaluating the attack.
"""

from numpy.random import choice

# Data for evaluating the attack.
n_sample_train = 3000
eval_data_idx=choice(len(imgs_train), n_sample_train)
members_samples, members_labels= imgs_train[eval_data_idx], labels_train_cat[eval_data_idx]
n_sample_train = 3000
eval_data_idx=choice(len(imgs_test), n_sample_train)
non_members_samples, non_members_labels= imgs_test[eval_data_idx], labels_test_cat[eval_data_idx]

"""#Impliment your attack based on the above steps"""



from art.estimators.classification.scikitlearn import ScikitlearnRandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from numpy.random import choice
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score, recall_score

def prepare_eval_data(imgs_train, imgs_test):
    n_members = min(3000, len(imgs_train))
    n_non_members = min(3000, len(imgs_test))

    eval_data_idx_members = choice(len(imgs_train), n_members, replace=False)
    members_samples = imgs_train[eval_data_idx_members]

    eval_data_idx_non_members = choice(len(imgs_test), n_non_members, replace=False)
    non_members_samples = imgs_test[eval_data_idx_non_members]


    members_samples = members_samples.reshape(members_samples.shape[0], -1)
    non_members_samples = non_members_samples.reshape(non_members_samples.shape[0], -1)

    return members_samples, non_members_samples


def build_shadow_models(n_shadow_models, train_data, train_labels):
    shadow_models = []
    validation_accuracies = []
    for _ in range(n_shadow_models):
        X_train, X_val, y_train, y_val = train_test_split(
            train_data,
            train_labels,
            train_size=0.5,
            stratify=train_labels
        )
        X_train = X_train.reshape(X_train.shape[0], -1)
        X_val = X_val.reshape(X_val.shape[0], -1)

        if y_train.ndim > 1:
            y_train = np.argmax(y_train, axis=1)
        if y_val.ndim > 1:
            y_val = np.argmax(y_val, axis=1)


        model = RandomForestClassifier()
        model.fit(X_train, y_train)

        art_model = ScikitlearnRandomForestClassifier(model)

        y_val_pred = model.predict(X_val)
        val_accuracy = accuracy_score(y_val, y_val_pred)


        validation_accuracies.append(val_accuracy)

        shadow_models.append((art_model, val_accuracy))

    return shadow_models, validation_accuracies


def create_attack_model(shadow_models, eval_data, eval_labels):
    features = []
    for model in shadow_models:
        sk_model = model[0].model
        predictions = sk_model.predict_proba(eval_data)
        features.append(predictions[:, 1])
    features = np.array(features).T

    attack_model = RandomForestClassifier()
    attack_model.fit(features, eval_labels)

    return attack_model


def evaluate_attack_model(attack_model, members, non_members):
    members_features = np.array([model[0].model.predict_proba(members)[:, 1] for model in shadow_models]).T
    non_members_features = np.array([model[0].model.predict_proba(non_members)[:, 1] for model in shadow_models]).T

    members_pred = attack_model.predict(members_features)
    non_members_pred = attack_model.predict(non_members_features)

    members_accuracy = accuracy_score(np.ones(len(members)), members_pred)
    non_members_accuracy = accuracy_score(np.zeros(len(non_members)), non_members_pred)

    return members_accuracy, non_members_accuracy



shadow_accuracies = {}
attack_performance = {}
attack_metrics = {}



for num_shadow_models in [1, 2, 5]:

    shadow_accuracies[num_shadow_models] = np.mean(validation_accuracies)


    members_accuracy, non_members_accuracy = evaluate_attack_model(attack_model, members_samples, non_members_samples)
    attack_performance[num_shadow_models] = (members_accuracy, non_members_accuracy)


    total_samples = len(members_samples) + len(non_members_samples)
    overall_accuracy = (members_accuracy * len(members_samples) + non_members_accuracy * len(non_members_samples)) / total_samples


    attack_performance[num_shadow_models] = (members_accuracy, non_members_accuracy, overall_accuracy)


    members_features = np.array([model[0].model.predict_proba(members_samples)[:, 1] for model in shadow_models]).T
    non_members_features = np.array([model[0].model.predict_proba(non_members_samples)[:, 1] for model in shadow_models]).T


    members_pred = attack_model.predict(members_features)
    non_members_pred = attack_model.predict(non_members_features)


    true_labels = np.concatenate([np.ones(len(members_samples)), np.zeros(len(non_members_samples))])
    pred_labels = np.concatenate([members_pred, non_members_pred])


    attack_precision = precision_score(true_labels, pred_labels)
    attack_recall = recall_score(true_labels, pred_labels)
    attack_metrics[num_shadow_models] = (attack_precision, attack_recall)


table_3 = {
    'Metric': ['Average Accuracy (using validation)', 'Members accuracy', 'Non-members accuracy', 'Overall accuracy', 'Attack precision', 'Attack recall'],
    1: [shadow_accuracies[1], attack_performance[1][0], attack_performance[1][1], attack_performance[1][2], attack_metrics[1][0], attack_metrics[1][1]],
    2: [shadow_accuracies[2], attack_performance[2][0], attack_performance[2][1], attack_performance[2][2], attack_metrics[2][0], attack_metrics[2][1]],
    5: [shadow_accuracies[5], attack_performance[5][0], attack_performance[5][1], attack_performance[5][2], attack_metrics[5][0], attack_metrics[5][1]],
}


for metric, v1, v2, v5 in zip(table_3['Metric'], table_3[1], table_3[2], table_3[5]):
    print(f"{metric}: {v1} (1 model), {v2} (2 models), {v5} (5 models)")

"""#Here is a code to calculate precision and recall
Make sure it is correct before using it

def calc_precision_recall(predicted, actual, positive_value=1):
    score = 0  # both predicted and actual are positive
    num_positive_predicted = 0  # predicted positive
    num_positive_actual = 0  # actual positive
    for i in range(len(predicted)):
        if predicted[i] == positive_value:
            num_positive_predicted += 1
        if actual[i] == positive_value:
            num_positive_actual += 1
        if predicted[i] == actual[i]:
            if predicted[i] == positive_value:
                score += 1

    if num_positive_predicted == 0:
        precision = 1
    else:
        precision = score / num_positive_predicted  # the fraction of predicted “Yes” responses that are correct
    if num_positive_actual == 0:
        recall = 1
    else:
        recall = score / num_positive_actual  # the fraction of “Yes” responses that are predicted correctly

    return precision, recall

#Task 4

We will leave the details of implimentation to you

Now, let's defend test defense with DP. We have built a DP-SGD model using the TensorFlow privacy library. The model is given to you, and you just need to analyze it. First, check the overall DP code and answer the below questions. Then, analyze the given DP model in terms of accuracy and resiliency to membership inference attacks. Use a label-only membership inference attack with 5 max-queries and the same setup as in Task 2.


2.	[5 pts] Measure the differential privacy guarantee of the given model.

3.	[5 pts] Calculate the model's performance under attacks and any other observations regarding the results.
"""

!pip install tensorflow-privacy

#import tensorflow as tf
#print(tf.__version__)
import tensorflow_privacy
print(tensorflow_privacy.__version__)
from tensorflow_privacy.privacy.analysis import compute_dp_sgd_privacy_lib


#from tensorflow_privacy.privacy.analysis import dp_accounting

import tensorflow as tf
import numpy as np
from tensorflow.keras.models import load_model, model_from_json
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import accuracy_score
from art.estimators.classification import TensorFlowV2Classifier
from tensorflow.keras.optimizers import Adam
import pickle

import tensorflow as tf
from tensorflow.keras.models import model_from_json
from art.estimators.classification import TensorFlowV2Classifier
import numpy as np
from sklearn.metrics import accuracy_score

dp_json_path = "drive/MyDrive/CS5331_CS4331/HW1/GTSRB_dataset/dp_model_architecture.json"
dp_weights_path = "drive/MyDrive/CS5331_CS4331/HW1/GTSRB_dataset/dp_model_weights.h5"


vgg_model_path = "drive/MyDrive/CS5331_CS4331/HW1/GTSRB_dataset/VGG_best.h5"


def load_dp_model(json_path, weights_path):
    with open(json_path, 'r') as json_file:
        model_json = json_file.read()
    model = tf.keras.models.model_from_json(model_json)
    model.load_weights(weights_path)
    return model


dp_model = load_dp_model(dp_json_path, dp_weights_path)


vgg_model = load_model(vgg_model_path)


dp_classifier = TensorFlowV2Classifier(
    model=dp_model,
    nb_classes=NUM_LABELS,
    input_shape=INPUT_SHAPE,
    clip_values=(0, 1)
)

vgg_classifier = TensorFlowV2Classifier(
    model=vgg_model,
    nb_classes=NUM_LABELS,
    input_shape=INPUT_SHAPE,
    clip_values=(0, 1)
)


def calculate_normal_accuracy(classifier, x_test, y_test):
    predictions = classifier.predict(x_test)
    return accuracy_score(np.argmax(y_test, axis=1), np.argmax(predictions, axis=1))


def perform_membership_inference(classifier, x_eval, y_eval, eval_label):

    predictions = classifier.predict(x_eval)
    prediction_probabilities = np.max(predictions, axis=1)


    member_mask = eval_label == 1
    non_member_mask = eval_label == 0

    member_accuracy = accuracy_score(np.argmax(y_eval[member_mask], axis=1),
                                     np.argmax(predictions[member_mask], axis=1))
    non_member_accuracy = accuracy_score(np.argmax(y_eval[non_member_mask], axis=1),
                                         np.argmax(predictions[non_member_mask], axis=1))
    overall_accuracy = accuracy_score(np.argmax(y_eval, axis=1), np.argmax(predictions, axis=1))

    return {
        'member_accuracy': member_accuracy,
        'non_member_accuracy': non_member_accuracy,
        'overall_accuracy': overall_accuracy
    }

def main():

    n_eval = 1500
    n_train = n_eval // 2
    n_test = n_eval - n_train


    train_indices = np.random.choice(len(imgs_train), n_train, replace=False)
    test_indices = np.random.choice(len(imgs_test), n_test, replace=False)

    x_eval = np.concatenate([imgs_train[train_indices], imgs_test[test_indices]])
    y_eval = np.concatenate([labels_train_cat[train_indices], labels_test_cat[test_indices]])
    eval_label = np.concatenate([np.ones(n_train), np.zeros(n_test)])


    print("\nCalculating normal accuracy on test set...")

    vgg_normal_accuracy = calculate_normal_accuracy(vgg_classifier, imgs_test, labels_test_cat)
    dp_normal_accuracy = calculate_normal_accuracy(dp_classifier, imgs_test, labels_test_cat)

    print(f"VGG16 Normal Accuracy: {vgg_normal_accuracy:.4f}")
    print(f"DP Model Normal Accuracy: {dp_normal_accuracy:.4f}")


    print("\nTesting DP model for membership inference...")
    dp_results = perform_membership_inference(
        classifier=dp_classifier,
        x_eval=x_eval,
        y_eval=y_eval,
        eval_label=eval_label
    )

    print("\nDP Model Membership Inference Results:")
    print(f"Member Accuracy: {dp_results['member_accuracy']:.4f}")
    print(f"Non-Member Accuracy: {dp_results['non_member_accuracy']:.4f}")
    print(f"Overall Accuracy: {dp_results['overall_accuracy']:.4f}")


    print("\nTesting VGG model for membership inference...")
    vgg_results = perform_membership_inference(
        classifier=vgg_classifier,
        x_eval=x_eval,
        y_eval=y_eval,
        eval_label=eval_label
    )

    print("\nVGG Model Membership Inference Results:")
    print(f"Member Accuracy: {vgg_results['member_accuracy']:.4f}")
    print(f"Non-Member Accuracy: {vgg_results['non_member_accuracy']:.4f}")
    print(f"Overall Accuracy: {vgg_results['overall_accuracy']:.4f}")


if __name__ == "__main__":
    main()